-   id: check-file-and-directory-names
    name: Check file names and directory names
    description: Check directory and file names are consistent
    entry: python3 check_file_and_directory_names/main.py
    language: python
    types: [file]
    exclude: ^.*$
    always_run: true
